Repository wp-cli/wp-super-cache-cli, pull requests merged in 2018-10, with the labels that each got.

#23 Ignore log files
  .gitignore
Labels: scope:distribution

#24 Improves command status
  src/WP_Super_Cache_Command.php
Labels: enhancement

#25 Fixes discrepancy between commands ena/dis and status
  src/WP_Super_Cache_Command.php
Labels: bug
